name: CI
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.7", "3.9", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user pipenv
          pipenv --python ${{ matrix.python-version }}
          pipenv install
      - name: Turn on 'editable' mode
        run: |
          pipenv install -e .
      - name: Fetch API Key for test
        run: |
          echo ${{secrets.TEST_API_KEY}}
        env:
          API_KEY: "${{secrets.TEST_API_KEY}}"

      - name: Test with pytest
        run: |
          pipenv run pip install pytest
          pipenv run python -m pytest
